### ISSUE TITLE
Incorrect backend status after receiving seats

### ISSUE THREAD

**Issue by piggydoughnut** [chips-blockchain/bet#156] opened 2020-08-18 03:22 UTC
## Issue
I am receiving backend status 0 after receiving the seats information on one of the player nodes.

## Frontend
<img width="1290" alt="Screen Shot 2020-08-18 at 3 21 49 PM" src="https://user-images.githubusercontent.com/2395326/90466762-afc41b00-e166-11ea-8ab0-dde12818ae4a.png">

## Backend log

```
chips@chips-01:~/bet/privatebet$ cd ~/bet/privatebet && ./bet player
ln is in sync with chips
Notary node status
1. 159.69.23.28 not active
2. 159.69.23.29 active
3. 159.69.23.30 active
4. 159.69.23.31 active
Finding the dealer
The dealer is :: 45.77.139.155
bet_player_backend::1508::stack_info_resp
bet_player_backend::1579::{
	"method":	"stack_info_resp",
	"id":	"77a99a1d3c514da9519d871ae315d299d7f95b3b324536ca6e4ae315df490f0f",
	"max_players":	2,
	"table_stack_in_chips":	0.01000000,
	"chips_tx_fee":	0.00050000,
	"legacy_m_of_n_msig_addr":	"bTKNTJdn81HcB9EAJCvjksWqYRdqysBhRK",
	"table_id":	"782d5c22c1fed9854f430327acb020d3274f318d21d8c47916b4e8ed5e641f88",
	"threshold_value":	2,
	"msig_addr_nodes":	["159.69.23.29", "159.69.23.30", "159.69.23.31"]
}
error code: -26
error message:
dust (code 64)
bet_player_handle_stack_info_resp::1384::txid::(null)
bet_player_backend::1508::tx_status
bet_player_backend::1605::unable make lock_in transaction
bet_player_backend::1508::dcv_state
bet_player_backend::1508::dcv_state
bet_player_backend::1508::dcv_state
bet_player_backend::1508::dcv_state
bet_player_backend::1508::stack_info_resp
bet_player_backend::1579::{
	"method":	"stack_info_resp",
	"id":	"404f7debd7242f7f331206a0c5db0779b89292ed25700db49982ce5d41d68725",
	"max_players":	2,
	"table_stack_in_chips":	0.01000000,
	"chips_tx_fee":	0.00050000,
	"legacy_m_of_n_msig_addr":	"bTKNTJdn81HcB9EAJCvjksWqYRdqysBhRK",
	"table_id":	"782d5c22c1fed9854f430327acb020d3274f318d21d8c47916b4e8ed5e641f88",
	"threshold_value":	2,
	"msig_addr_nodes":	["159.69.23.29", "159.69.23.30", "159.69.23.31"]
}
lws_callback_http_player:1243::LWS_CALLBACK_ESTABLISHED
bet_gui_init_message::1214::{
	"method":	"warning",
	"warning_num":	0
}
lws_callback_http_player::1248::Writing data to the GUI
bet_player_backend::1508::tx_status
bet_player_backend::1508::seats_info_resp
lws_callback_http_player::1248::Writing data to the GUI
bet_player_frontend::1158::{
	"method":	"walletInfo"
}
bet_player_wallet_info::1139::{
	"method":	"walletInfo",
	"addr":	"RBHQ88xgPj9vuYKUMfdnCuwRePsqhZva4c",
	"balance":	0.01947823,
	"backend_status":	0,
	"max_players":	2,
	"table_stack_in_chips":	10,
	"table_id":	"782d5c22c1fed9854f430327acb020d3274f318d21d8c47916b4e8ed5e641f88"
}
lws_callback_http_player::1248::Writing data to the GUI
lws_callback_http_player:1243::LWS_CALLBACK_ESTABLISHED
bet_gui_init_message::1214::{
	"method":	"warning",
	"warning_num":	0
}
lws_callback_http_player::1248::Writing data to the GUI
bet_player_backend::1508::join_res
bet_update_seat_info::1497::{
	"method":	"seats",
	"seats":	[{
			"name":	"player1",
			"seat":	0,
			"chips":	0,
			"empty":	1,
			"playing":	0
		}, {
			"name":	"player2",
			"seat":	1,
			"chips":	10,
			"empty":	0,
			"playing":	0
		}]
}
lws_callback_http_player::1248::Writing data to the GUI
bet_player_frontend::1158::{
	"method":	"walletInfo"
}
bet_player_wallet_info::1139::{
	"method":	"walletInfo",
	"addr":	"RBHQ88xgPj9vuYKUMfdnCuwRePsqhZva4c",
	"balance":	0.01947823,
	"backend_status":	0,
	"max_players":	2,
	"table_stack_in_chips":	10,
	"table_id":	"782d5c22c1fed9854f430327acb020d3274f318d21d8c47916b4e8ed5e641f88"
}
lws_callback_http_player::1248::Writing data to the GUI
bet_player_backend::1508::stack
bet_player_frontend::1158::{
	"method":	"player_join",
	"gui_playerID":	1
}
bet_player_process_player_join::1082::{
	"method":	"warning",
	"warning_num":	0
}
lws_callback_http_player::1248::Writing data to the GUI
```

**Comment by piggydoughnut** [comment] 2020-10-08 22:13
Just reproduced again.  @sg777 
Here are the logs.

[dcv.txt](https://github.com/chips-blockchain/bet/files/5351503/dcv.txt)
[player1.txt](https://github.com/chips-blockchain/bet/files/5351504/player1.txt)
[player2.txt](https://github.com/chips-blockchain/bet/files/5351505/player2.txt)



Player2
<img width="1781" alt="Screen Shot 2020-10-09 at 11 12 47 AM" src="https://user-images.githubusercontent.com/2395326/95518843-6d111780-0a20-11eb-93b9-f845813bcdb4.png">

**Comment by sg777** [comment] 2020-10-13 13:03
This issue has been fixed in the latest commits.

**Comment by satindergrewal** [comment] 2021-02-16 04:58
@piggydoughnut if this issue is resolved, and you confirmed it is, then please close it.

**Comment by sg777** [comment] 2021-02-23 11:49
You see in the player2 logs, tx is waiting to commit, since the tx is not committed the BE is sending the warning:0 saying that BE is not ready yet. It's not any error of the sort.

Below is the enum that declares the warning:
```
enum bet_warnings { 
backend_not_ready = 0, 
seat_already_taken, 
insufficient_funds, 
table_is_full 
};
```
Whenever you receive any of these warnings, please make sure to convey to the user accordingly.

**Closed by sg777** 2021-02-23 11:49 UTC
Labels: P0, bug
