### ISSUE TITLE
Segmentation fault after one of the players folds: Error occured in processing the payout tx 

### ISSUE THREAD

**Issue by piggydoughnut** [chips-blockchain/bet#191] opened 2021-03-08 22:51 UTC
## Issue
DCV node crashed after one of the players performed fold.

DCV Error message
```
chips_create_payout_tx::1248::Error occured in processing the payout tx ::"02000000023f268a8bf905c1305cef038d644b3e1fc68e5880a5934b220a73a658067b57ca0000000000ffffffff2a4a395cd9bc29fb4fd732daf8d2131734811ab2365becae4bc1a38b2308c3770000000000ffffffff056b030000000000001976a914be4a423803575ac39db6f58854f1ff8ad1b00af088ac410a00000000000017a914d20c53477c21c5600d14c6d191f5f0ccf7c920a48700350c000000000017a91402a0674d48df135136f893c2ac294d34b8026c6887847e11000000000017a914f025a76f451c372116835ba6d3125c52026a08a5870000000000000000fd10026a4d0c027b0a09227461626c655f6964223a092238383663653133316637353231306232646633383861363765656566376665343335643833373439653831356538366235386233646530313038666639666134222c0a09226d6178706c6179657273223a09322c0a0922726f756e6473223a09312c0a092267616d655f7374617465223a095b7b0a090909226265745f616374696f6e73223a095b332c20375d2c0a09090922706c617965725f6361726473223a095b33392c2034342c2032332c2031372c2031332c202d312c202d315d0a09097d2c207b0a090909226265745f616374696f6e73223a095b352c20305d2c0a09090922706c617965725f6361726473223a095b302c20332c2032332c2031372c2031332c202d312c202d315d0a09097d5d2c0a0922706c617965725f696473223a095b2264643034376638663431653334323166333837663232393664366239653437646463366264356238363361663839333061633962386565643730303663643237222c202238303465373338643364323863303035333234353464303238653737396439396137643934323436376565663665313164636634306237643832303432363638225d2c0a09227468726573686f6c645f76616c7565223a09322c0a09226d7369675f616464725f6e6f646573223a095b2235312e3232322e3135302e3530222c202235312e3232322e3135302e3531225d0a7d00000000"
bet_dcv_poker_winner::1101::payout_tx_info::{
	"method":	"payout_tx",
	"table_id":	"886ce131f75210b2df388a67eeef7fe435d83749e815e86b58b3de0108ff9fa4"
}
bet_evaluate_hand::1235::{
	"method":	"finalInfo",
	"showInfo":	{
		"allHoleCardsInfo":	[[null, null], [null, null]],
		"boardCardInfo":	[null, null, null, null, null]
	},
	"win_amount":	4,
	"winners":	[1]
}
bet_dcv_backend_thrd::1690::player_active
bet_dcv_backend_thrd::1690::player_active
Segmentation fault
```

## Steps to reproduce

Play a hand with two players, make one of them fold.

## Logs

[dcv.txt](https://github.com/chips-blockchain/bet/files/6104645/dcv.txt)
[player1.txt](https://github.com/chips-blockchain/bet/files/6104646/player1.txt)
[player2.txt](https://github.com/chips-blockchain/bet/files/6104647/player2.txt)

**Comment by sg777** [comment] 2021-03-09 00:09
I couldn't able to reproduce this issue, can you please run the dealer node using gdb and please share the backtrace log to debug.

**Comment by sg777** [comment] 2021-03-09 00:21
I see you getting this error, because you are not connecting the dealer from the GUI. Try play the game by connecting the dealer with the GUI.

**Comment by sg777** [comment] 2021-03-09 00:44
This issue has been fixed in https://github.com/chips-blockchain/bet/pull/192.

**Closed by sg777** 2021-03-09 00:44 UTC
Labels: alpha, bug
